### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by s1204IT**
## Summary of the Pull Request

- Add Japanese translation
- Fix build command typo

### CODE REVIEW

**Comment by s1204IT** [comment]
Build failed😢 

<details><summary>Log</summary>

```
PS W:\Documents\WSA-Sideloader> nuitka --standalone sideloader.py --enable-plugin=tk-inter --windows-disable-console --windows-product-name="WSA Sideloader" --windows-icon-from-ico=icon.ico --windows-file-description="WSA Sideloader"
Nuitka-Options:INFO: Used command line options: --standalone sideloader.py --enable-plugin=tk-inter --windows-disable-console --windows-product-name="WSA Sideloader" --windows-icon-from-ico=icon.ico --windows-file-description="WSA Sideloader"
Nuitka:INFO: Starting Python compilation with Nuitka '1.6.4' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: tk-inter: Injecting pre-module load code for module 'PySimpleGUI':
Nuitka-Plugins:INFO: tk-inter:     Need to make sure we set environment variables for TCL.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka-Plugins:INFO: tk-inter: Injecting pre-module load code for module 'tkinter':
Nuitka-Plugins:INFO: tk-inter:     Need to make sure we set environment variables for TCL.
Nuitka-Plugins:INFO: implicit-imports: Injecting post-module load code for module 'PySide6.QtCore':
Nuitka-Plugins:INFO: implicit-imports:     According to Yaml configuration.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Running '"C:\\Users\\Administrator\\AppData\\Local\\Nuitka\\Nuitka\\Cache\\downloads\\ccache\\v4.6\\ccache.exe" "C:\\Users\\Administrator\\AppData\\Local\\Nuitka\\Nuitka\\Cache\\downloads\\gcc\\x86_64\\11.3.0-14.0.3-10.0.0-msvcrt-r3\\mingw64\\bin\\gcc.exe" -o "module.PySimpleGUI.PySimpleGUI.o" -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -fcompare-debug-second -O3 -D_WIN32_WINNT=0x0501 -D__NUITKA_NO_ASSERT__ -D_NUITKA_WINMAIN_ENTRY_POINT -D_NUITKA_STANDALONE -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=155 -D_NUITKA_EXE -D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 "-IC:\\Program Files\\Python311\\include" -I. -IC:\\Users\\ADMINI~1\\AppData\\Roaming\\Python\\PYTHON~1\\SITE-P~1\\nuitka\\build\\include -IC:\\Users\\ADMINI~1\\AppData\\Roaming\\Python\\PYTHON~1\\SITE-P~1\\nuitka\\build\\static_src "module.PySimpleGUI.PySimpleGUI.c"' took 157.18 seconds
Nuitka-Scons:INFO: Backend linking program with 235 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 565 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 187
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 48
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\__main__.py", line 155, in <module>    main()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\__main__.py", line 141, in main
    MainControl.main()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\MainControl.py", line 1105, in main    _main()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\MainControl.py", line 996, in _main    executePostProcessing()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\PostProcessing.py", line 318, in executePostProcessing
    executePostProcessingResources(manifest=manifest, onefile=False)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\PostProcessing.py", line 248, in executePostProcessingResources
    addVersionInfoResource(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python311\site-packages\nuitka\utils\WindowsResources.py", line 599, in addVersionInfoResource
    assert product_version
AssertionError
```

</details>

Unfortunately, I am not familiar with Python and need help.

**Comment by infinitepower18** [comment]
Try this command: `nuitka --standalone sideloader.py --enable-plugin=tk-inter --windows-disable-console --windows-company-name=infinitepower18 --windows-product-name="WSA Sideloader" --windows-icon-from-ico=icon.ico --windows-product-version=1.4.0 --windows-file-version=1.4.0 --windows-file-description="WSA Sideloader"`

Just checked it and two issues:

1. Invalid escape character error shows for `helpText` and `wsaNotDetectedWin11`:

image

2. The text on the buttons are cut off due to some bug with these sort of languages, so as a workaround add some spaces at the start and end of the string e.g. `"installButton": "  インストール  "` (usually two spaces but I found that more spaces are needed for longer strings like `instAppsButton`)

Other than these, looking great so far!

image

image

**Comment by s1204IT** [comment]
Thanks for your support.
Validate now.

**Comment by s1204IT** [comment]
```
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 235 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 468 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 234
Nuitka-Postprocessing:INFO: Adding 9 icon(s) from icon file 'icon.ico'.
Nuitka-Plugins:INFO: tk-inter: Included 87 data files due to Tk needed for tkinter usage.
Nuitka-Plugins:INFO: tk-inter: Included 835 data files due to Tcl needed for tkinter usage.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka:INFO: Keeping build directory 'sideloader.build'.
Nuitka:INFO: Successfully created 'sideloader.dist\sideloader.exe'.
```
Build is successful.
But, cannot launching app.

I tried with administrator privileges, but it didn't work.

**Comment by s1204IT** [comment]
As for the string issue, I will check it out as I get it working.

**Comment by infinitepower18** [comment]
> ```
> Nuitka:INFO: Completed Python level compilation and optimization.
> Nuitka:INFO: Generating source code for C backend compiler.
> Nuitka:INFO: Running data composer tool for optimal constant value handling.
> Nuitka:INFO: Running C compilation via Scons.
> Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
> Nuitka-Scons:INFO: Backend linking program with 235 files (no progress information available for this stage).
> Nuitka-Scons:INFO: Compiled 468 C files using ccache.
> Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 234
> Nuitka-Postprocessing:INFO: Adding 9 icon(s) from icon file 'icon.ico'.
> Nuitka-Plugins:INFO: tk-inter: Included 87 data files due to Tk needed for tkinter usage.
> Nuitka-Plugins:INFO: tk-inter: Included 835 data files due to Tcl needed for tkinter usage.
> Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
> Nuitka:INFO: Keeping build directory 'sideloader.build'.
> Nuitka:INFO: Successfully created 'sideloader.dist\sideloader.exe'.
> ```
> 
> Build is successful. But, cannot launching app.
> 
> I tried with administrator privileges, but it didn't work.

Did you copy the icon.ico, aapt.exe files, locales, platform-tools folders to the sideloader.dist folder? It won't work without these

**Comment by s1204IT** [comment]
> > ```
> > Nuitka:INFO: Completed Python level compilation and optimization.
> > Nuitka:INFO: Generating source code for C backend compiler.
> > Nuitka:INFO: Running data composer tool for optimal constant value handling.
> > Nuitka:INFO: Running C compilation via Scons.
> > Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
> > Nuitka-Scons:INFO: Backend linking program with 235 files (no progress information available for this stage).
> > Nuitka-Scons:INFO: Compiled 468 C files using ccache.
> > Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 234
> > Nuitka-Postprocessing:INFO: Adding 9 icon(s) from icon file 'icon.ico'.
> > Nuitka-Plugins:INFO: tk-inter: Included 87 data files due to Tk needed for tkinter usage.
> > Nuitka-Plugins:INFO: tk-inter: Included 835 data files due to Tcl needed for tkinter usage.
> > Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
> > Nuitka:INFO: Keeping build directory 'sideloader.build'.
> > Nuitka:INFO: Successfully created 'sideloader.dist\sideloader.exe'.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Build is successful. But, cannot launching app.
> > I tried with administrator privileges, but it didn't work.
> 
> Did you copy the icon.ico, aapt.exe files, locales, platform-tools folders to the sideloader.dist folder? It won't work without these

Of cource.

```
sideloader.dist
├─certifi
├─locales
├─PIL
├─platform-tools
├─PySide6
├─shiboken6
├─tcl
│  ├─encoding
│  ├─http1.0
│  ├─msgs
│  ├─opt0.4
│  └─tzdata
│      ├─Africa
│      ├─America
│      │  ├─Argentina
│      │  ├─Indiana
│      │  ├─Kentucky
│      │  └─North_Dakota
│      ├─Antarctica
│      ├─Arctic
│      ├─Asia
│      ├─Atlantic
│      ├─Australia
│      ├─Brazil
│      ├─Canada
│      ├─Chile
│      ├─Etc
│      ├─Europe
│      ├─Indian
│      ├─Mexico
│      ├─Pacific
│      ├─SystemV
│      └─US
├─tcl8
│  ├─8.4
│  │  └─platform
│  ├─8.5
│  └─8.6
└─tk
    ├─images
    ├─msgs
    └─ttk
```
But, cannot launch app :(

**Comment by infinitepower18** [comment]
Ok, I have to check in Windows Sandbox. For now try running sideloader.py directly:
`python sideloader.py`

**Comment by s1204IT** [comment]
> Ok, I have to check in Windows Sandbox. For now try running sideloader.py directly: `python sideloader.py`

```
PS W:\Documents\WSA-Sideloader> python .\sideloader.py
Traceback (most recent call last):
  File "W:\Documents\WSA-Sideloader\sideloader.py", line 33, in <module>
    strings = json.load(json_file)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 11 column 185 (char 436)
```

**Comment by infinitepower18** [comment]
> 1. Invalid escape character error shows for `helpText` and `wsaNotDetectedWin11`:
> 
> image

This needs to be fixed before it will work.

**Comment by s1204IT** [comment]
I finally understood what it meant.
I am sorry.

**Comment by s1204IT** [comment]
Mistakes could be corrected!

image
But, this time there are words that are not translated.

**Comment by infinitepower18** [comment]
> Mistakes could be corrected!
> 
> image But, this time there are words that are not translated.

I have fixed the view button, please check with the latest sideloader.py file.

Regarding enabled/disabled, this will soon be fixed once I verify the settings save properly regardless of language. But the enabled/disabled strings are already in the json so updating the strings shouldn't be a problem.

**Comment by s1204IT** [comment]
I have tried, but there is no change.

**Comment by infinitepower18** [comment]
Displaying fine for me, if you are running the exe then you will need to build again.

image

I forgot to include the browse button on the main screen so added `browseButton` to the json, sideloader.py updated as well to reflect this change.

**Comment by s1204IT** [comment]
image
The "Browse" has been resolved, but "enabled"/"disabled" is still not resolved.

**Comment by infinitepower18** [comment]
> image The "Browse" has been resolved, but "enabled"/"disabled" is still not resolved.

Should be fixed now.

**Comment by s1204IT** [comment]
It fixed!!
image

**Comment by s1204IT** [comment]
All translations and improvements have been completed!

**Comment by infinitepower18** [comment]
Thanks a lot! Will test it in a bit before merging.

If you can also help translate the Microsoft Store description that would be great. The description will be updated so I’ll send you the updated description in a while.

**Comment by s1204IT** [comment]
> Thanks a lot! Will test it in a bit before merging.
> 
> If you can also help translate the Microsoft Store description that would be great. The description will be updated so I’ll send you the updated description in a while.

Of cource!
Any time you're ready! xD

**Review by infinitepower18 — APPROVED** [review]

**Comment by infinitepower18** [comment]
Thanks a lot for the translation! I have also enabled Japanese in the installer.

image

**Pull request merged**
